#!/usr/bin/env python
# -*- coding: utf-8 -*-
import pygame
from pygame.sprite import Group
import sys
from settings import Settings
from chequer import Chequer
import functions as f
from button import Button

def run_game():
    pygame.init()
    settings = Settings()


    # 创建存储棋子的编组
    pieces = Group()

    screen = pygame.display.set_mode((settings.screen_width,settings.screen_height),4,0)
    chequer = Chequer(screen,pieces)
    pygame.display.set_caption("五子棋")
    background = pygame.image.load("background3.jpg").convert()
    button = Button(screen,'悔棋')
    while True:
        f.check_events(chequer,pieces)
        #screen.fill((settings.bg_color))
        screen.blit(background,(0,0))
        chequer.lines()
        chequer.cirs()
        chequer.get_mouse_pos(pieces)
        for pos in chequer.poslist_b:
            chequer.set_piece(pos,chequer.black)
        for pos in chequer.poslist_w:
            chequer.set_piece(pos,chequer.white)

        button.draw_botton()

        pygame.display.flip()

run_game()
